
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - nginx-app-deployment.yaml
patches:
  - target:
      kind: Deployment
      name: nginx-app-deployment    
    patch: |-
      - op: add
        path: /metadata/name
        value: nginx-web-deployment
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: nginx:1.21.0
      - op: replace 
        path: /spec/replicas
        value: 5
      - op: add
        path: /spec/template/metadata/labels/name
        value: sanket



