---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - target:
       kind: Deployment
       name: apache-deployment
    path: label-patch.yaml
resources:
  - Deployment.yaml
