apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - db-depl.yaml
  - db-service.yaml
patches:
  - api-patch.yaml

secretGenerator:
  - name: db-creds
    literals:
      - password=password1


