# steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-t', 'gcr.io/$PROJECT_ID/hello-world', '.']

# - name: 'gcr.io/cloud-builders/kustomize'
#   args: ['build', 'overlays/production', '-o', 'manifests']

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['apply', '-f', 'manifests']
#   env:
#   - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
#   - 'CLOUDSDK_CONTAINER_CLUSTER=sanket-cluster'

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['container', 'images', 'add-tag', 'gcr.io/$PROJECT_ID/hello-world:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/hello-world:latest']

# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['container', 'clusters', 'get-credentials', 'sanket-cluster']

# - name: 'gcr.io/cloud-builders/kubectl'
#   args: ['set', 'image', 'deployment/hello-world', 'hello-world=gcr.io/$PROJECT_ID/hello-world:$COMMIT_SHA']


steps:
- name: 'asia.gcr.io/k8s-artifacts-prod/kustomize/kustomize:v4.5.7'
  args: ['build', 'kustomize-example-8-multi-cluster-deployments/overlays/dev-cluster/', '-o', 'kustomize-example-8-multi-cluster-deployments/overlays/d-cluster']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kustomize-example-8-multi-cluster-deployments/overlays/d-cluster']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sanket-cluster'

- name: 'asia.gcr.io/k8s-artifacts-prod/kustomize/kustomize:v4.5.7'
  args: ['build', 'kustomize-example-8-multi-cluster-deployments/overlays/prod-cluster/', '-o', 'kustomize-example-8-multi-cluster-deployments/overlays/p-cluster']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'kustomize-example-8-multi-cluster-deployments/overlays/p-cluster']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-south1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=sanket-prod-cluster'

options:
  logging: CLOUD_LOGGING_ONLY

