apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - apache-depl.yaml
  - apache-svc.yaml
nameSuffix: d-cluster



#our previous value of apache will be overriden from apache -> apache-webserver